// Mock events — used when VITE_SUPABASE_URL is not set.
// Replace with real Supabase data in production.

export const MOCK_EVENTS = [
  {
    id: '1', title: 'Arsenal vs Chelsea', category_slug: 'sports',
    category_label: 'Sports', category_icon: '🏆',
    ai_summary: 'Premier League clash streamed live from London.',
    starts_at: new Date().setHours(15, 0, 0, 0),
    is_free: false, tags: ['football', 'live', 'premier-league'],
    venue_name: 'Online', venue_city: 'Online', price_min: null,
  },
  {
    id: '2', title: 'Nairobi Marathon 2026', category_slug: 'sports',
    category_label: 'Sports', category_icon: '🏆',
    ai_summary: 'Annual Nairobi city marathon starting at Uhuru Park.',
    starts_at: new Date().setHours(6, 0, 0, 0),
    is_free: false, tags: ['running', 'marathon', 'outdoor'],
    venue_name: 'Uhuru Park', venue_city: 'Nairobi', price_min: 500,
  },
  {
    id: '3', title: 'Free Pet Vaccination Drive', category_slug: 'vet',
    category_label: 'Vets & Pets', category_icon: '🐾',
    ai_summary: 'Free rabies & distemper vaccines for dogs and cats.',
    starts_at: new Date().setHours(9, 0, 0, 0),
    is_free: true, tags: ['vaccination', 'dogs', 'cats', 'free'],
    venue_name: 'Karen Veterinary Clinic', venue_city: 'Nairobi', price_min: 0,
  },
  {
    id: '4', title: 'Exotic Animal Checkup Clinic', category_slug: 'vet',
    category_label: 'Vets & Pets', category_icon: '🐾',
    ai_summary: 'Specialist checkups for reptiles, birds and small mammals.',
    starts_at: new Date().setHours(10, 0, 0, 0),
    is_free: false, tags: ['exotic', 'reptiles', 'birds'],
    venue_name: 'Mombasa Pet Centre', venue_city: 'Mombasa', price_min: 800,
  },
  {
    id: '5', title: 'Jazz Night at The Alchemist', category_slug: 'music',
    category_label: 'Music', category_icon: '🎷',
    ai_summary: 'Live Afro-jazz and fusion sets in Westlands.',
    starts_at: new Date().setHours(19, 30, 0, 0),
    is_free: false, tags: ['jazz', 'live-music', 'afro', 'westlands'],
    venue_name: 'The Alchemist', venue_city: 'Nairobi', price_min: 500,
  },
  {
    id: '6', title: 'Online Piano Masterclass', category_slug: 'music',
    category_label: 'Music', category_icon: '🎷',
    ai_summary: 'Free beginner-to-intermediate piano session via Zoom.',
    starts_at: new Date().setHours(16, 0, 0, 0),
    is_free: true, tags: ['piano', 'online', 'free', 'masterclass'],
    venue_name: 'Online', venue_city: 'Online', price_min: 0,
  },
  {
    id: '7', title: 'Nairobi Street Food Festival', category_slug: 'food',
    category_label: 'Food', category_icon: '🍢',
    ai_summary: 'Dozens of Kenyan street food vendors at the CBD grounds.',
    starts_at: new Date().setHours(11, 0, 0, 0),
    is_free: true, tags: ['street-food', 'kenyan', 'free', 'outdoor'],
    venue_name: 'Nairobi CBD Grounds', venue_city: 'Nairobi', price_min: 0,
  },
  {
    id: '8', title: 'Vegan Cooking Workshop', category_slug: 'food',
    category_label: 'Food', category_icon: '🍢',
    ai_summary: 'Hands-on plant-based cooking class in Lavington.',
    starts_at: new Date().setHours(14, 0, 0, 0),
    is_free: false, tags: ['vegan', 'cooking', 'workshop'],
    venue_name: 'Lavington Kitchen Studio', venue_city: 'Nairobi', price_min: 1500,
  },
  {
    id: '9', title: 'Neighbourhood Clean-Up Drive', category_slug: 'community',
    category_label: 'Community', category_icon: '🤝',
    ai_summary: 'Community volunteers clean up Eastleigh streets.',
    starts_at: new Date().setHours(8, 0, 0, 0),
    is_free: true, tags: ['volunteer', 'environment', 'free'],
    venue_name: 'Eastleigh', venue_city: 'Nairobi', price_min: 0,
  },
  {
    id: '10', title: 'Youth Mentorship Forum', category_slug: 'community',
    category_label: 'Community', category_icon: '🤝',
    ai_summary: 'Online forum connecting Nairobi youth with industry mentors.',
    starts_at: new Date().setHours(17, 0, 0, 0),
    is_free: true, tags: ['mentorship', 'youth', 'online', 'free'],
    venue_name: 'Online', venue_city: 'Online', price_min: 0,
  },
  {
    id: '11', title: 'Free Blood Pressure Screening', category_slug: 'health',
    category_label: 'Health', category_icon: '🩺',
    ai_summary: 'Walk-in BP and BMI checks at Kenyatta National Hospital.',
    starts_at: new Date().setHours(9, 0, 0, 0),
    is_free: true, tags: ['health', 'screening', 'free', 'walk-in'],
    venue_name: 'Kenyatta National Hospital', venue_city: 'Nairobi', price_min: 0,
  },
  {
    id: '12', title: 'Tech Skills Bootcamp', category_slug: 'education',
    category_label: 'Education', category_icon: '💻',
    ai_summary: 'Free online bootcamp covering web dev and AI basics.',
    starts_at: new Date().setHours(13, 0, 0, 0),
    is_free: true, tags: ['tech', 'coding', 'ai', 'free', 'online'],
    venue_name: 'Online', venue_city: 'Online', price_min: 0,
  },
]

export const CATEGORIES = [
  { slug: 'all',       label: 'All events',  icon: '✦' },
  { slug: 'sports',    label: 'Sports',      icon: '🏆' },
  { slug: 'vet',       label: 'Vets & Pets', icon: '🐾' },
  { slug: 'music',     label: 'Music',       icon: '🎷' },
  { slug: 'food',      label: 'Food',        icon: '🍢' },
  { slug: 'community', label: 'Community',   icon: '🤝' },
  { slug: 'health',    label: 'Health',      icon: '🩺' },
  { slug: 'education', label: 'Education',   icon: '💻' },
]
